### ISSUE TITLE
/chats POST method에 body로 뭘 줘야하나요??

### ISSUE THREAD

**Issue by know-nothing-TT** [snuwebprogramming/homework2#1]
message랑 created를 주면 되는건가요...? return 해주는 값을 써주신 것 같은데 그럼 뭘 body로 넘겨줘야할지...
스펙 설명란에 login처럼 {name} 이런게 없어서 여쭤봅니다

**Comment by realcom** [comment]
답이 늦었는데

message 만 주시면 됩니다. 헤더에 Authorization set해서..
