### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by gajagajago** [snuwebprogramming/homework2#14]
eslint가 criteria에 없어서 안 한 상태로 제출했는데 criteria에 생겼더라고요..
이거 어떻게 해야되나요 ㅜㅜ

**Comment by gajagajago** [comment]
> eslint랑 node_modules를 안 지웠는데...

이미 제출해버렸어요... ㅜ.ㅜ

**Comment by gajagajago** [comment]
((esLint 이번에는 그냥 안써도되믄은들끄유.... 팀프로즉트뜨는 잘쓸게여ㅜㅜ..)

**Comment by realcom** [comment]
엌 네. 추가를 좀 늦게 해서 eslint부분은 반영하지 않도록 하겠습니다.
