### ISSUE TITLE
제출 기한 살짝만 늘려주시면 안되나요??

### ISSUE THREAD

**Issue by taewonee** [snuwebprogramming/homework2#15]
제가 지금 이미 할 시간이 없어서 마무리했는데,
eslint 추가 같은건 업데이트가 살짝 늦게 된 것 같습니다...
감사합니다...

**Comment by gajagajago** [comment]
eslint가 criteria에 직전에 올라온 것 같아서.. 이미 제출한 사람들은 수정이 안 됐을것 같습니다.

**Comment by realcom** [comment]
엌 네. 일정 연장은 애매할 것 같고 eslint부분은 반영하지 않도록 하겠습니다.

**Comment by taewonee** [comment]
압도적 감사!
