### ISSUE TITLE
자기가 한 말은 오른쪽에

### ISSUE THREAD

**Issue by know-nothing-TT** [snuwebprogramming/homework2#2]
나와야하는건가요 아니면 왼쪽에 다른 사람 채팅처럼 나와도 되는건가요??
오픈채팅을 한번도 안 써봐서 모르겠군요

**Comment by realcom** [comment]
자기가 했던 말인 걸로 명시적으로 표현만 되면 됩니다. (음영, 오른쪽 배치 등...)
