### ISSUE TITLE
GET /chats API 질문

### ISSUE THREAD

**Issue by ysm1180** [snuwebprogramming/homework2#3]
orderBy 파라미터를 asc, desc 둘 중 아무거나로 줘도 아무런 결과 변화가 없어서
최신 100개를 못 불러옵니다....

**Comment by chang02** [comment]
같은질문입니다.. 조건에 맞는 결과가 100개가 넘는경우 최근 100개로 응답하도록 api 수정 가능할까요??!

**Comment by realcom** [comment]
you send order params, then you can retrieve reverse ordered message.

for example)

https://snu-web-random-chat.herokuapp.com/chats?order=desc
