### ISSUE TITLE
한번 로그인 시 사용된 아이디는 재활용 불가능한가요? 

### ISSUE THREAD

**Issue by gajagajago** [snuwebprogramming/homework2#6]
??

**Comment by gajagajago** [comment]
로그인 이력이 있을 시, 자동으로 로그인 시도가 무슨 말인지도 조금 모르겠어요 ㅠ

**Comment by zigsong** [comment]
저도 로그인 이력이 있을 시~ 이게 무슨 뜻인지 모르겠습니다

**Comment by realcom** [comment]
한 번 로그아웃한 계정이 재로그인하는건 고려하지 않으셔도 됩니다.

로그인 후, 새로고침 시 로그인이 유지되야 된다는 의미입니다.
